import{S as m}from"./assets/vendor-CgTBfC_f.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function c(e){if(e.ep)return;e.ep=!0;const a=s(e);fetch(e.href,a)}})();const u=[{url:"https://cdn.pixabay.com/photo/2019/05/14/16/43/rchids-4202820_1280.jpg",alt:"Hokkaido Flower"},{url:"https://cdn.pixabay.com/photo/2019/05/14/22/05/container-4203677_1280.jpg",alt:"Container Haulage Freight"},{url:"https://cdn.pixabay.com/photo/2019/05/16/09/47/beach-4206785_1280.jpg",alt:"Aerial Beach View"},{url:"https://cdn.pixabay.com/photo/2016/11/18/16/19/flowers-1835619_1280.jpg",alt:"Flower Blooms"},{url:"https://cdn.pixabay.com/photo/2018/09/13/10/36/mountains-3674334_1280.jpg",alt:"Alpine Mountains"},{url:"https://cdn.pixabay.com/photo/2019/05/16/23/04/landscape-4208571_1280.jpg",alt:"Mountain Lake Sailing"},{url:"https://cdn.pixabay.com/photo/2019/05/17/09/27/the-alps-4209272_1280.jpg",alt:"Alpine Spring Meadows"},{url:"https://cdn.pixabay.com/photo/2019/05/16/21/10/landscape-4208255_1280.jpg",alt:"Nature Landscape"},{url:"https://cdn.pixabay.com/photo/2019/05/17/04/35/lighthouse-4208843_1280.jpg",alt:"Lighthouse Coast Sea"}],d=document.querySelector(".gallery"),g=u.map(t=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${t.url}">
        <img
          class="gallery-image"
          src="${t.url}"
          alt="${t.alt}"
        />
      </a>
    </li>
  `).join("");d.insertAdjacentHTML("beforeend",g);new m(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"});const o={email:"",message:""},l=document.querySelector(".feedback-form"),n="feedback-form-state",p=localStorage.getItem(n);if(p){const t=JSON.parse(p);o.email=t.email,o.message=t.message,l.elements.email.value=o.email,l.elements.message.value=o.message}l.addEventListener("input",t=>{const{name:r,value:s}=t.target;o[r]=s.trim(),localStorage.setItem(n,JSON.stringify(o))});l.addEventListener("submit",t=>{if(t.preventDefault(),!o.email||!o.message){alert("Fill please all fields");return}console.log(o),localStorage.removeItem(n),o.email="",o.message="",l.reset()});
//# sourceMappingURL=index.js.map
